export const petOptions = {
  dog: {
    label: "หมา",
    breeds: [
      { label: "ชิวาวา", value: "Chihuahua" },
      { label: "โกลเด้นรีทรีฟเวอร์", value: "Golden Retriever" },
      { label: "ปอมเมอเรเนียน", value: "Pomeranian" },
      { label: "ไซบีเรียนฮัสกี้", value: "Siberian Husky" },
      { label: "ชิสุ", value: "Shih Tzu" },
      { label: "บีเกิ้ล", value: "Beagle" },
      { label: "พุดเดิ้ล", value: "Poodle" },
      { label: "บูลด็อก", value: "Bulldog" },
      { label: "คอร์กี้", value: "Corgi" },
      { label: "ไทยหลังอาน", value: "Thai Ridgeback" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  cat: {
    label: "แมว",
    breeds: [
      { label: "เปอร์เซีย", value: "Persian" },
      { label: "สก็อตติชโฟลด์", value: "Scottish Fold" },
      { label: "เมนคูน", value: "Maine Coon" },
      { label: "บริติชช็อตแฮร์", value: "British Shorthair" },
      { label: "ไทยวิเชียรมาศ", value: "Siamese" },
      { label: "อเมริกันช็อตแฮร์", value: "American Shorthair" },
      { label: "เบงกอล", value: "Bengal" },
      { label: "แร็กดอลล์", value: "Ragdoll" },
      { label: "เอ็กโซติก", value: "Exotic Shorthair" },
      { label: "คาร์เน็กซ์เร็กซ์", value: "Cornish Rex" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  bird: {
    label: "นก",
    breeds: [
      { label: "นกหงส์หยก", value: "Budgerigar" },
      { label: "นกเลิฟเบิร์ด", value: "Lovebird" },
      { label: "นกค็อกคาเทล", value: "Cockatiel" },
      { label: "นกแก้วมาคอว์", value: "Macaw" },
      { label: "นกฟินช์", value: "Finch" },
      { label: "นกคีรีบูน", value: "Canary" },
      { label: "นกกระตั้ว", value: "Cockatoo" },
      { label: "นกซันคอนัวร์", value: "Sun Conure" },
      { label: "นกจาบคาหัวเขียว", value: "Blue-throated Barbet" },
      { label: "นกขุนทอง", value: "Hill Myna" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  rabbit: {
    label: "กระต่าย",
    breeds: [
      { label: "ฮอลแลนด์ลอป", value: "Holland Lop" },
      { label: "ไลอ้อนเฮด", value: "Lionhead" },
      { label: "เร็กซ์", value: "Rex" },
      { label: "เฟลมมิชไจแอนท์", value: "Flemish Giant" },
      { label: "มินิเร็กซ์", value: "Mini Rex" },
      { label: "อังกฤษแองโกรา", value: "English Angora" },
      { label: "ดัตช์", value: "Dutch" },
      { label: "เนเธอร์แลนด์ดวอร์ฟ", value: "Netherland Dwarf" },
      { label: "โพลิช", value: "Polish" },
      { label: "อเมริกันโชลิน", value: "American Chinchilla" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  raccoon: {
    label: "แรคคูน",
    breeds: [{ label: "นอร์ธอเมริกันแรคคูน", value: "North American Raccoon" }],
  },
  hedgehog: {
    label: "เม่นแคระ",
    breeds: [
      { label: "แอฟริกันพิกมี่", value: "African Pygmy Hedgehog" },
      { label: "อัลบิโนพิกมี่", value: "Albino Pygmy Hedgehog" },
      { label: "ซอลท์แอนด์เปปเปอร์", value: "Salt and Pepper" },
      { label: "ซินนามอน", value: "Cinnamon" },
      { label: "แอพริคอต", value: "Apricot" },
    ],
  },
  duck: {
    label: "เป็ด",
    breeds: [
      { label: "เป็ดปักกิ่ง", value: "Pekin Duck" },
      { label: "เป็ดเทศ", value: "Muscovy Duck" },
      { label: "เป็ดคาเยน", value: "Cayuga Duck" },
      { label: "เป็ดคอลลี", value: "Khaki Campbell" },
      { label: "เป็ดอินเดียนรันเนอร์", value: "Indian Runner" },
      { label: "เป็ดคัลเลอร์", value: "Call Duck" },
      { label: "เป็ดบ้านไทย", value: "Thai Native Duck" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  turtle: {
    label: "เต่า",
    breeds: [
      { label: "ซัลคาต้า", value: "Sulcata Tortoise" },
      { label: "เรเดียเต็ด", value: "Radiated Tortoise" },
      { label: "เสือดาว", value: "Leopard Tortoise" },
      { label: "ริเวอร์เทอร์เทิล", value: "River Turtle" },
      { label: "อินเดียนสตาร์", value: "Indian Star Tortoise" },
      { label: "อัลดาบร้า", value: "Aldabra Tortoise" },
      { label: "เรดฟุต", value: "Red-footed Tortoise" },
      { label: "เชอร์รีเฮด", value: "Cherry Head Tortoise" },
      { label: "กล่องเต่าเอเชีย", value: "Asian Box Turtle" },
      { label: "กล่องเต่าอเมริกา", value: "American Box Turtle" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  chicken: {
    label: "ไก่",
    breeds: [
      { label: "ไก่ชน", value: "Fighting Cock" },
      { label: "ไก่แจ้", value: "Bantam" },
      { label: "ไก่เบตง", value: "Betong Chicken" },
      { label: "ไก่ซิลกี้", value: "Silkie" },
      { label: "ไก่บาร์พลีมัธร็อก", value: "Barred Plymouth Rock" },
      { label: "ไก่โร๊ดไอส์แลนด์เรด", value: "Rhode Island Red" },
      { label: "ไก่เล็กฮอร์น", value: "Leghorn" },
      { label: "ไก่บาร์นีเวลเดอร์", value: "Barnevelder" },
      { label: "ไก่ซัมมาทร้า", value: "Sumatra Chicken" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
  squirrel: {
    label: "กระรอก",
    breeds: [
      { label: "กระรอกไทย", value: "Thai Squirrel" },
      { label: "กระรอกบิน", value: "Flying Squirrel" },
      { label: "กระรอกสวน", value: "Plantain Squirrel" },
      { label: "อื่นๆ", value: "Other" },
      { label: "ไม่ทราบ", value: "Unknown" },
    ],
  },
};
export const haveCollar = [
  { label: "มี", value: "havecollar" },
  { label: "ไม่มี", value: "nothavecollar" },
];
export const postOptions = [
  { label: "ตามหาสัตว์หาย", value: "findpet" },
  { label: "ตามหาเจ้าของ", value: "findowner" },
  { label: "ตามหาบ้าน", value: "findhome" },
];
export const sexOptions = [
  { label: "ชาย", value: "male" },
  { label: "หญิง", value: "female" },
];
export const colorOptions = [
  { key: "orange", label: "ส้ม" },
  { key: "black", label: "ดำ" },
  { key: "white", label: "ขาว" },
  { key: "gray", label: "เทา" },
  { key: "red", label: "แดง" },
  { key: "gold", label: "ทอง" },
  { key: "yellow", label: "เหลือง" },
  { key: "cream", label: "ครีม" },
  { key: "brown", label: "น้ำตาล" },
  { key: "beige", label: "นวล" },
  { key: "green", label: "เขียว" },
  { key: "blue", label: "น้ำเงิน" },
  { key: "skyblue", label: "ฟ้า" },
  { key: "lightyellow", label: "เหลืองสลิต" },
  { key: "siamese", label: "วิเชียรมาศ" },
  { key: "striped", label: "ลายเสือ" },
];
